### PR TITLE
🌱 Implement full cluster artifact gathering for both clusters after each test run

### LINKED ISSUE #333: Collect details about failed e2e test clusters in CI
Our e2e tests do not collect necessary debugging information, required to determine conditions, when the jobs has failed.
We need a tool comparable to must-gather in order to do so.

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
kind/chore

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #333 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
@richardcase PTAL

File: test/e2e/suites/v2prov/v2prov_test.go [hunk 1]
```diff
@@ -155,6 +164,13 @@ var _ = Describe("[v2prov] [Azure] Creating a cluster with v2prov should still w
 		}, rancherConnectRes)
 		Expect(rancherConnectRes.Error).NotTo(HaveOccurred(), "Failed getting nodes with Rancher Kubeconfig")
 		Expect(rancherConnectRes.ExitCode).To(Equal(0), "Getting nodes return non-zero exit code")
+	})
+
+	AfterEach(func() {
+		err := testenv.CollectArtifacts(ctx, rancherKubeconfig.TempFilePath, path.Join(flagVals.ArtifactFolder, setupClusterResult.BootstrapClusterProxy.GetName(), clusterName))
+		if err != nil {
+			fmt.Printf("Failed to artifacts for the child cluster: %v\n", err)
```
Comment (salasberryfin) [inline test/e2e/suites/v2prov/v2prov_test.go:172]:
```suggestion
			fmt.Printf("Failed to collect artifacts for the child cluster: %v\n", err)
```

File: test/framework/rancher_helpers.go [hunk 2]
```diff
@@ -101,6 +107,101 @@ func RancherGetClusterKubeconfig(ctx context.Context, input RancherGetClusterKub
 	result.TempFilePath = tempFile.Name()
 }
 
+// RancherGetOriginalKubeconfig will get the unmodified Kubeconfig for a cluster from Rancher.
+func RancherGetOriginalKubeconfig(ctx context.Context, input RancherGetClusterKubeconfigInput, result *RancherGetClusterKubeconfigResult) {
```
Comment (salasberryfin) [inline test/framework/rancher_helpers.go:111]: Would it make sense to have this and `RancherGetClusterKubeconfig` into a single function? Looks like the differences in the logic are rather small. Maybe we can have an extra field in `RancherGetClusterKubeconfigInput` to set whether we're getting one kubeconfig or the other? Just wondering if this would be viable and so we minimize code repetition.

**Review by salasberryfin — COMMENTED** [review]
LGTM. Just a couple of nitpicking comments.

File: test/framework/rancher_helpers.go (hunk 2 above)
Comment (salasberryfin) [reply test/framework/rancher_helpers.go:111]: Thanks, that makes sense.

Comment (Danil-Grigorev) [reply test/framework/rancher_helpers.go:111]: Generally speaking the separate kubeconfig is required only for one scenario, when a rancher API server is not available. So it is not required to use the second method, if this failure scenario is not assumed.

**Review by salasberryfin — APPROVED** [review]

**Review by richardcase — APPROVED** [review]
